name: OP Chapter Pipeline

on:
  schedule:
    - cron: '*/30 * * * 4,5,6'
  workflow_dispatch:

jobs:
  chapter-search:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Get repo
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'

      - name: Install Tesseract
        run: sudo apt-get install -y tesseract-ocr

      - name: Check cache venv
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: venv-${{ runner.os }}-


      - name: Finish Python venv
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: python -m venv venv

      - name: Install dependencies
        run: |
          venv/bin/pip install --upgrade pip
          venv/bin/pip install -r requirements.txt

      - name: Search Chapter
        env:
          smtp_pass: ${{ secrets.SMTP_PASS }}
          db_name: ${{ secrets.DB_NAME }}
        run: venv/bin/python chapter_search.py
